// src/Utils/quranData.js

export const SURAH_LIST = [
  { nomor: 1, namaArab: "الفاتحة", namaLatin: "Al-Fatihah", jumlahAyat: 7 },
  { nomor: 2, namaArab: "البقرة", namaLatin: "Al-Baqarah", jumlahAyat: 286 },
  { nomor: 3, namaArab: "آل عمران", namaLatin: "Ali 'Imran", jumlahAyat: 200 },
  { nomor: 4, namaArab: "النساء", namaLatin: "An-Nisa", jumlahAyat: 176 },
  { nomor: 5, namaArab: "المائدة", namaLatin: "Al-Ma'idah", jumlahAyat: 120 },
  { nomor: 6, namaArab: "الأنعام", namaLatin: "Al-An'am", jumlahAyat: 165 },
  { nomor: 7, namaArab: "الأعراف", namaLatin: "Al-A'raf", jumlahAyat: 206 },
  { nomor: 8, namaArab: "الأنفال", namaLatin: "Al-Anfal", jumlahAyat: 75 },
  { nomor: 9, namaArab: "التوبة", namaLatin: "At-Taubah", jumlahAyat: 129 },
  { nomor: 10, namaArab: "يونس", namaLatin: "Yunus", jumlahAyat: 109 },
  { nomor: 11, namaArab: "هود", namaLatin: "Hud", jumlahAyat: 123 },
  { nomor: 12, namaArab: "يوسف", namaLatin: "Yusuf", jumlahAyat: 111 },
  { nomor: 13, namaArab: "الرعد", namaLatin: "Ar-Ra'd", jumlahAyat: 43 },
  { nomor: 14, namaArab: "إبراهيم", namaLatin: "Ibrahim", jumlahAyat: 52 },
  { nomor: 15, namaArab: "الحجر", namaLatin: "Al-Hijr", jumlahAyat: 99 },
  { nomor: 16, namaArab: "النحل", namaLatin: "An-Nahl", jumlahAyat: 128 },
  { nomor: 17, namaArab: "الإسراء", namaLatin: "Al-Isra", jumlahAyat: 111 },
  { nomor: 18, namaArab: "الكهف", namaLatin: "Al-Kahf", jumlahAyat: 110 },
  { nomor: 19, namaArab: "مريم", namaLatin: "Maryam", jumlahAyat: 98 },
  { nomor: 20, namaArab: "طه", namaLatin: "Taha", jumlahAyat: 135 },
  { nomor: 21, namaArab: "الأنبياء", namaLatin: "Al-Anbiya", jumlahAyat: 112 },
  { nomor: 22, namaArab: "الحج", namaLatin: "Al-Hajj", jumlahAyat: 78 },
  { nomor: 23, namaArab: "المؤمنون", namaLatin: "Al-Mu'minun", jumlahAyat: 118 },
  { nomor: 24, namaArab: "النور", namaLatin: "An-Nur", jumlahAyat: 64 },
  { nomor: 25, namaArab: "الفرقان", namaLatin: "Al-Furqan", jumlahAyat: 77 },
  { nomor: 26, namaArab: "الشعراء", namaLatin: "Asy-Syu'ara", jumlahAyat: 227 },
  { nomor: 27, namaArab: "النمل", namaLatin: "An-Naml", jumlahAyat: 93 },
  { nomor: 28, namaArab: "القصص", namaLatin: "Al-Qasas", jumlahAyat: 88 },
  { nomor: 29, namaArab: "العنكبوت", namaLatin: "Al-Ankabut", jumlahAyat: 69 },
  { nomor: 30, namaArab: "الروم", namaLatin: "Ar-Rum", jumlahAyat: 60 },
  { nomor: 31, namaArab: "لقمان", namaLatin: "Luqman", jumlahAyat: 34 },
  { nomor: 32, namaArab: "السجدة", namaLatin: "As-Sajdah", jumlahAyat: 30 },
  { nomor: 33, namaArab: "الأحزاب", namaLatin: "Al-Ahzab", jumlahAyat: 73 },
  { nomor: 34, namaArab: "سبإ", namaLatin: "Saba'", jumlahAyat: 54 },
  { nomor: 35, namaArab: "فاطر", namaLatin: "Fatir", jumlahAyat: 45 },
  { nomor: 36, namaArab: "يس", namaLatin: "Ya-Sin", jumlahAyat: 83 },
  { nomor: 37, namaArab: "الصافات", namaLatin: "As-Saffat", jumlahAyat: 182 },
  { nomor: 38, namaArab: "ص", namaLatin: "Sad", jumlahAyat: 88 },
  { nomor: 39, namaArab: "الزمر", namaLatin: "Az-Zumar", jumlahAyat: 75 },
  { nomor: 40, namaArab: "غافر", namaLatin: "Ghafir", jumlahAyat: 85 },
  { nomor: 41, namaArab: "فصلت", namaLatin: "Fussilat", jumlahAyat: 54 },
  { nomor: 42, namaArab: "الشورى", namaLatin: "Ash-Shura", jumlahAyat: 53 },
  { nomor: 43, namaArab: "الزخرف", namaLatin: "Az-Zukhruf", jumlahAyat: 89 },
  { nomor: 44, namaArab: "الدخان", namaLatin: "Ad-Dukhan", jumlahAyat: 59 },
  { nomor: 45, namaArab: "الجاثية", namaLatin: "Al-Jathiyah", jumlahAyat: 37 },
  { nomor: 46, namaArab: "الأحقاف", namaLatin: "Al-Ahqaf", jumlahAyat: 35 },
  { nomor: 47, namaArab: "محمد", namaLatin: "Muhammad", jumlahAyat: 38 },
  { nomor: 48, namaArab: "الفتح", namaLatin: "Al-Fath", jumlahAyat: 29 },
  { nomor: 49, namaArab: "الحجرات", namaLatin: "Al-Hujurat", jumlahAyat: 18 },
  { nomor: 50, namaArab: "ق", namaLatin: "Qaf", jumlahAyat: 45 },
  { nomor: 51, namaArab: "الذاريات", namaLatin: "Adh-Dhariyat", jumlahAyat: 60 },
  { nomor: 52, namaArab: "الطور", namaLatin: "At-Tur", jumlahAyat: 49 },
  { nomor: 53, namaArab: "النجم", namaLatin: "An-Najm", jumlahAyat: 62 },
  { nomor: 54, namaArab: "القمر", namaLatin: "Al-Qamar", jumlahAyat: 55 },
  { nomor: 55, namaArab: "الرحمن", namaLatin: "Ar-Rahman", jumlahAyat: 78 },
  { nomor: 56, namaArab: "الواقعة", namaLatin: "Al-Waqi'ah", jumlahAyat: 96 },
  { nomor: 57, namaArab: "الحديد", namaLatin: "Al-Hadid", jumlahAyat: 29 },
  { nomor: 58, namaArab: "المجادلة", namaLatin: "Al-Mujadilah", jumlahAyat: 22 },
  { nomor: 59, namaArab: "الحشر", namaLatin: "Al-Hasyr", jumlahAyat: 24 },
  { nomor: 60, namaArab: "الممتحنة", namaLatin: "Al-Mumtahanah", jumlahAyat: 13 },
  { nomor: 61, namaArab: "الصف", namaLatin: "As-Saff", jumlahAyat: 14 },
  { nomor: 62, namaArab: "الجمعة", namaLatin: "Al-Jumu'ah", jumlahAyat: 11 },
  { nomor: 63, namaArab: "المنافقون", namaLatin: "Al-Munafiqun", jumlahAyat: 11 },
  { nomor: 64, namaArab: "التغابن", namaLatin: "At-Taghabun", jumlahAyat: 18 },
  { nomor: 65, namaArab: "الطلاق", namaLatin: "At-Talaq", jumlahAyat: 12 },
  { nomor: 66, namaArab: "التحريم", namaLatin: "At-Tahrim", jumlahAyat: 12 },
  { nomor: 67, namaArab: "الملك", namaLatin: "Al-Mulk", jumlahAyat: 30 },
  { nomor: 68, namaArab: "القلم", namaLatin: "Al-Qalam", jumlahAyat: 52 },
  { nomor: 69, namaArab: "الحاقة", namaLatin: "Al-Haqqah", jumlahAyat: 52 },
  { nomor: 70, namaArab: "المعارج", namaLatin: "Al-Ma'arij", jumlahAyat: 44 },
  { nomor: 71, namaArab: "نوح", namaLatin: "Nuh", jumlahAyat: 28 },
  { nomor: 72, namaArab: "الجن", namaLatin: "Al-Jinn", jumlahAyat: 28 },
  { nomor: 73, namaArab: "المزمل", namaLatin: "Al-Muzzammil", jumlahAyat: 20 },
  { nomor: 74, namaArab: "المدثر", namaLatin: "Al-Muddaththir", jumlahAyat: 56 },
  { nomor: 75, namaArab: "القيامة", namaLatin: "Al-Qiyamah", jumlahAyat: 40 },
  { nomor: 76, namaArab: "الإنسان", namaLatin: "Al-Insan", jumlahAyat: 31 },
  { nomor: 77, namaArab: "المرسلات", namaLatin: "Al-Mursalat", jumlahAyat: 50 },
  { nomor: 78, namaArab: "النبإ", namaLatin: "An-Naba'", jumlahAyat: 40 },
  { nomor: 79, namaArab: "النازعات", namaLatin: "An-Nazi'at", jumlahAyat: 46 },
  { nomor: 80, namaArab: "عبس", namaLatin: "'Abasa", jumlahAyat: 42 },
  { nomor: 81, namaArab: "التكوير", namaLatin: "At-Takwir", jumlahAyat: 29 },
  { nomor: 82, namaArab: "الإنفطار", namaLatin: "Al-Infitar", jumlahAyat: 19 },
  { nomor: 83, namaArab: "المطففين", namaLatin: "Al-Mutaffifin", jumlahAyat: 36 },
  { nomor: 84, namaArab: "الإنشقاق", namaLatin: "Al-Inshiqaq", jumlahAyat: 25 },
  { nomor: 85, namaArab: "البروج", namaLatin: "Al-Buruj", jumlahAyat: 22 },
  { nomor: 86, namaArab: "الطارق", namaLatin: "At-Tariq", jumlahAyat: 17 },
  { nomor: 87, namaArab: "الأعلى", namaLatin: "Al-A'la", jumlahAyat: 19 },
  { nomor: 88, namaArab: "الغاشية", namaLatin: "Al-Ghashiyah", jumlahAyat: 26 },
  { nomor: 89, namaArab: "الفجر", namaLatin: "Al-Fajr", jumlahAyat: 30 },
  { nomor: 90, namaArab: "البلد", namaLatin: "Al-Balad", jumlahAyat: 20 },
  { nomor: 91, namaArab: "الشمس", namaLatin: "Ash-Shams", jumlahAyat: 15 },
  { nomor: 92, namaArab: "الليل", namaLatin: "Al-Lail", jumlahAyat: 21 },
  { nomor: 93, namaArab: "الضحى", namaLatin: "Ad-Duha", jumlahAyat: 11 },
  { nomor: 94, namaArab: "الشرح", namaLatin: "Ash-Sharh", jumlahAyat: 8 },
  { nomor: 95, namaArab: "التين", namaLatin: "At-Tin", jumlahAyat: 8 },
  { nomor: 96, namaArab: "العلق", namaLatin: "Al-'Alaq", jumlahAyat: 19 },
  { nomor: 97, namaArab: "القدر", namaLatin: "Al-Qadr", jumlahAyat: 5 },
  { nomor: 98, namaArab: "البينة", namaLatin: "Al-Bayyinah", jumlahAyat: 8 },
  { nomor: 99, namaArab: "الزلزلة", namaLatin: "Az-Zalzalah", jumlahAyat: 8 },
  { nomor: 100, namaArab: "العاديات", namaLatin: "Al-'Adiyat", jumlahAyat: 11 },
  { nomor: 101, namaArab: "القارعة", namaLatin: "Al-Qari'ah", jumlahAyat: 11 },
  { nomor: 102, namaArab: "التكاثر", namaLatin: "At-Takathur", jumlahAyat: 8 },
  { nomor: 103, namaArab: "العصر", namaLatin: "Al-'Asr", jumlahAyat: 3 },
  { nomor: 104, namaArab: "الهمزة", namaLatin: "Al-Humazah", jumlahAyat: 9 },
  { nomor: 105, namaArab: "الفيل", namaLatin: "Al-Fil", jumlahAyat: 5 },
  { nomor: 106, namaArab: "قريش", namaLatin: "Quraisy", jumlahAyat: 4 },
  { nomor: 107, namaArab: "الماعون", namaLatin: "Al-Ma'un", jumlahAyat: 7 },
  { nomor: 108, namaArab: "الكوثر", namaLatin: "Al-Kawthar", jumlahAyat: 3 },
  { nomor: 109, namaArab: "الكافرون", namaLatin: "Al-Kafirun", jumlahAyat: 6 },
  { nomor: 110, namaArab: "النصر", namaLatin: "An-Nasr", jumlahAyat: 3 },
  { nomor: 111, namaArab: "المسد", namaLatin: "Al-Masad", jumlahAyat: 5 },
  { nomor: 112, namaArab: "الإخلاص", namaLatin: "Al-Ikhlas", jumlahAyat: 4 },
  { nomor: 113, namaArab: "الفلق", namaLatin: "Al-Falaq", jumlahAyat: 5 },
  { nomor: 114, namaArab: "الناس", namaLatin: "An-Nas", jumlahAyat: 6 }
];

// Map 30 Juz berdasarkan urutan surat
export const JUZ_MAP = {
  1: { dari: 1, sampai: 2 },
  2: { dari: 2, sampai: 2 },
  3: { dari: 2, sampai: 3 },
  4: { dari: 3, sampai: 4 },
  5: { dari: 4, sampai: 5 },
  6: { dari: 5, sampai: 6 },
  7: { dari: 6, sampai: 7 },
  8: { dari: 7, sampai: 8 },
  9: { dari: 8, sampai: 9 },
  10: { dari: 9, sampai: 11 },
  11: { dari: 11, sampai: 12 },
  12: { dari: 12, sampai: 14 },
  13: { dari: 14, sampai: 16 },
  14: { dari: 16, sampai: 18 },
  15: { dari: 17, sampai: 18 },
  16: { dari: 18, sampai: 20 },
  17: { dari: 21, sampai: 22 },
  18: { dari: 23, sampai: 25 },
  19: { dari: 25, sampai: 27 },
  20: { dari: 27, sampai: 29 },
  21: { dari: 29, sampai: 33 },
  22: { dari: 33, sampai: 36 },
  23: { dari: 36, sampai: 39 },
  24: { dari: 39, sampai: 41 },
  25: { dari: 41, sampai: 45 },
  26: { dari: 46, sampai: 51 },
  27: { dari: 51, sampai: 57 },
  28: { dari: 58, sampai: 66 },
  29: { dari: 67, sampai: 77 },
  30: { dari: 78, sampai: 114 }
};
